export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GET_ALL_SPECIALITYS = 'GET_ALL_ESPECIALITYS'
export const GET_ALL_COURSES = 'GET_ALL_COURSES'
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS'


export const GET_POST = 'GET_POST'
export const GET_SPECIALITY = 'GET_ESPECIALITY'
export const GET_COURSE = 'GET_COURSE'
export const GET_TEACHER = 'GET_TEACHER'
export const GET_FRAGMENT = 'GET_FRAGMENT'

